### ISSUE TITLE
Doesn't work with TypeScript 4.x

### ISSUE THREAD

**Issue by svzi** [unlight/eslint-plugin-ngxs-style-guide#1]
Hi there!

Thanks for the great plugin @unlight !

We're already using it in some of our TypeScript 3.x projects. We wanted to use it in a new project with TypeScript 4.x as well, but sadly the plugin itself have a dependency to TypeScript 3.x. Could you please fix it and allow TypeScript 4.x as well?

Best,
Sven

**Comment by svzi** [comment]
@unlight Thanks a lot for the very fast support. Sadly it looks like the new version is not working with TypeScript 3.x anymore. Is there any specific reason you dropped the support of TypeScript 3.x? Is that really necessary? Couldn't the plugin work with >= 3.x?

**Comment by unlight** [comment]
@svzi 
I think it should work with TS 3.
Changed dependency to `>=3` (please install v2.0.1)

**Comment by svzi** [comment]
@unlight Great, it looks good and works fine. Thanks a lot for your support. 🎉
