### ISSUE TITLE
new "no-pipe-dispatch" rule

### ISSUE THREAD

**Issue by svzi** [unlight/eslint-plugin-ngxs-style-guide#2]
Hi @unlight ,

could you please describe the new rule, that you've added with release 2.0 of this great plugin: `ngxs-style-guide/no-pipe-dispatch`? Maybe you get a source or explanation by hand, showing why it's important to avoid a `pipe(...)` after a `dispatch(...)`?

I'm asking because I thought this plugin serves as an ESLint plugin for the official best practices: https://www.ngxs.io/recipes/style-guide (even if this plugin is not authored by the NGXS creator) And I can't find a recommendation regarding the pipe-dispatch there.

Best,
Sven

**Comment by unlight** [comment]
Honestly, I don't remember why it exists.
When I updated packages, I realized that it has unpublished changes.
I'll try to check commits of the old project for which this plugin was created, maybe I can find roots...

**Comment by svzi** [comment]
That could be really helpful, thanks. Another approach would be to not mark the new rule as recommended, just in case you don't remember why it exists anymore. Because I can't see anything "bad" with a `pipe()` after an `dispatch()`. But don't get me wrong, I'm always happy to learn something new and avoid bad practices. 👍

**Comment by unlight** [comment]
Unfortunately, I could not find any useful information about this rule.
It will be removed from recommended in next version

**Comment by svzi** [comment]
Thanks @unlight
