### ISSUE TITLE
ESLint fails to run with plugin in Angular 13 project

### ISSUE THREAD

**Issue by elianora** [unlight/eslint-plugin-ngxs-style-guide#4]
# Recreate Steps

1. Create a new Angular 13 project using `ng new`
2. Add ESLint to the project using `ng add @angular-eslint/schematics`
3. Install plugin using `npm install --save-dev eslint-plugin-ngxs-style-guide`
4. Add plugin to ESLint configuration file
5. Attempt to run via `ng lint` or `npm run lint`

## Error Message

```console
An unhandled exception occurred: 
  Failed to load plugin 'ngxs-style-guide' declared in '.eslintrc.json#overrides[0]': 
    Class extends value undefined is not a constructor or null

Referenced from: <project_path>\.eslintrc.json
See "<temp_dir>\ng-mlwbyZ\angular-errors.log" for further details.
```

## Environment Information

- Node.js version: `16.13.0`
- Angular CLI version: `13.0.3`
- eslint version: `8.2.0`
- eslint-plugin-ngxs-style-guide version: `2.0.2`
- Platform: Windows 10

## ESLint Configuration File
```json
{
  "root": true,
  "ignorePatterns": ["projects/**/*"],
  "overrides": [
    {
      "files": ["*.ts"],
      "parserOptions": {
        "project": ["tsconfig.json"],
        "createDefaultProgram": true
      },
      "extends": [
        "plugin:rxjs/recommended",
        "plugin:ngxs-style-guide/recommended",
        "plugin:@angular-eslint/recommended",
        "plugin:@angular-eslint/template/process-inline-templates"
      ],
      "plugins": ["ngxs-style-guide", "rxjs"],
      "rules": {
        "@angular-eslint/directive-selector": [
          "error",
          {
            "type": "attribute",
            "prefix": "app",
            "style": "camelCase"
          }
        ],
        "@angular-eslint/component-selector": [
          "error",
          {
            "type": "element",
            "prefix": "app",
            "style": "kebab-case"
          }
        ],
        "rxjs/no-unsafe-takeuntil": [
          "error",
          {
            "alias": ["untilDestroyed"]
          }
        ],
        "quotes": [
          2,
          "single",
          {
            "avoidEscape": true,
            "allowTemplateLiterals": true
          }
        ],
        "indent": ["error", 4],
        "init-declarations": "off"
      }
    },
    {
      "files": ["*.html"],
      "extends": ["plugin:@angular-eslint/template/recommended"],
      "rules": {}
    }
  ]
}
```

**Comment by svzi** [comment]
This error is not limited to Angular 13. It also happens with Angular 12 and the newest eslint and eslint-angular plugins.

@unlight I'm sure you're already aware of https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#changes-to-shorthand-property-ast-format, but I wanted to share it just in case you're not.

It would be nice to see this fixed soon. Thanks for your great work!

**Comment by unlight** [comment]
Try v3.0.0 https://github.com/unlight/eslint-plugin-ngxs-style-guide/releases/tag/v3.0.0

**Comment by svzi** [comment]
@unlight Awesome! Thanks a lot for the ultra fast support. 🎉
